#!/usr/bin/env python3
"""bubble_shield_setup_mini.py — set up the Mac-mini read-distribution TIER.

Run ONCE on the client's Mac mini (the sole indexer). It:
  1. Copies bubble_shield_minid.py + the engine to a STABLE path (~/.bubble_shield/
     daemon/) so a plugin update / Cowork GC can't strand the launchd job.
  2. Writes + loads a LaunchAgent (com.bubbleshield.minid) that runs minid at login
     and KEEPS IT ALIVE (KeepAlive=true — a read daemon must ALWAYS be up; a mini
     reboot / macOS update must not silently kill every employee's read access).
  3. Verifies minid is actually serving (/health) before declaring success.

CRITICAL DIFFERENCE from nerd/gemmad launchd jobs:
  - KeepAlive is UNCONDITIONAL (true), not {SuccessfulExit:false}. nerd/gemmad
    idle-shut-down (exit 0) ON PURPOSE to free RAM; minid must NEVER be down.
  - minid runs on STOCK macOS python3 (3.9) — it's stdlib + the pure-python engine
    (shadow_store/known_pii_store), NO ML deps. So it does NOT need the 3.12 venv.
  - --host / --root / --port are per-install → passed as args, baked into the plist.

Usage (on the mini):
  python3 bubble_shield_setup_mini.py --host <mini-tailscale-ip> \
      --root <path-to-protected-vault> [--port 8377]
  # --host: the mini's Tailscale IP (tailscale ip -4). NEVER 0.0.0.0.
  # --root: the protected folder minid resolves index_request rel_paths under
  #         (the Dropbox clients folder).
  # --uninstall: remove the LaunchAgent + stop minid.
"""
from __future__ import annotations
import argparse
import os
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

BUBBLE_SHIELD_HOME = Path(os.environ.get("BUBBLE_SHIELD_HOME",
                                         Path.home() / ".bubble_shield"))
MINID_LABEL = "com.bubbleshield.minid"
MINID_PLIST = Path.home() / "Library" / "LaunchAgents" / f"{MINID_LABEL}.plist"
DAEMON_ROOT = BUBBLE_SHIELD_HOME / "daemon"
# minid script goes in daemon/scripts/; the engine MUST go where minid's own
# _vendor() resolves it — otherwise a stale copy at that path silently wins.
#   minid at daemon/scripts/bubble_shield_minid.py does, at import time:
#     _vendor() = Path(__file__).parent.parent / "vendor"  == daemon/vendor
#     sys.path.insert(0, _vendor())   ← PRIORITY over PYTHONPATH
# So the engine's canonical home is daemon/vendor/bubble_shield. Installing it
# anywhere else (the old daemon/scripts/bubble_shield) means minid never sees the
# fresh engine and, if a stale daemon/vendor/bubble_shield exists, loads THAT
# (the #761 signature: pre-fix engine → _passphrase()=None → plaintext → 0 shadows).
DAEMON_SCRIPTS_DIR = DAEMON_ROOT / "scripts"
DAEMON_VENDOR_DIR = DAEMON_ROOT / "vendor"          # == minid's _vendor()
DAEMON_ENGINE_DIR = DAEMON_VENDOR_DIR / "bubble_shield"
# minid + the pure-python engine it imports (shadow_store, known_pii_store, +deps).
# We copy the WHOLE vendored bubble_shield package to be safe — it's small and
# pure-python, and this is the stable copy launchd points at.
VENDOR_SRC = Path(__file__).resolve().parent.parent / "vendor" / "bubble_shield"


def log(msg: str) -> None:
    print(msg, flush=True)


def _stop_running_minid() -> None:
    """Bootout/unload the LaunchAgent BEFORE copying source.

    minid runs KeepAlive=true, so on a RE-install it is LIVE while we overwrite
    its source — a running interpreter can regenerate __pycache__ mid-copy and
    the fresh source ends up shadowed by stale bytecode. Stop it first; ignore
    errors (first install: not loaded yet)."""
    # `bootout` is the modern spelling; `unload` covers older macOS. Both no-op
    # (non-zero) if the job isn't loaded — that's fine on a first install.
    uid = os.getuid()
    subprocess.run(["launchctl", "bootout", f"gui/{uid}/{MINID_LABEL}"],
                   capture_output=True)
    subprocess.run(["launchctl", "unload", str(MINID_PLIST)], capture_output=True)


def _purge_pyc(root: Path) -> int:
    """Remove every __pycache__ dir and stray *.pyc under root.

    Belt-and-suspenders beyond copytree's ignore_patterns: a stale .pyc that is
    NEWER than the fresh source makes CPython load old bytecode. copytree only
    protects the files IT writes; anything pre-existing under the daemon tree (or
    regenerated by a still-running minid) must be swept explicitly."""
    removed = 0
    for pyc in root.rglob("*.pyc"):
        try:
            pyc.unlink()
            removed += 1
        except OSError:
            pass
    for cache in root.rglob("__pycache__"):
        if cache.is_dir():
            shutil.rmtree(cache, ignore_errors=True)
    return removed


def _install_to_stable_path() -> Path:
    """Copy minid + the engine into ~/.bubble_shield/daemon so launchd never points
    at the ephemeral per-session plugin cache (Cowork GCs it on every update).

    The engine lands at daemon/vendor/bubble_shield — the EXACT path minid's own
    _vendor() resolves and sys.path.insert(0)s ahead of PYTHONPATH. Aligning the
    two is the #761 fix: one canonical engine dir both agree on."""
    # 1. Stop the (possibly running) daemon so we copy against a quiescent tree.
    _stop_running_minid()

    DAEMON_SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    DAEMON_VENDOR_DIR.mkdir(parents=True, exist_ok=True)

    src_minid = Path(__file__).resolve().parent / "bubble_shield_minid.py"
    dst_minid = DAEMON_SCRIPTS_DIR / "bubble_shield_minid.py"
    shutil.copy2(src_minid, dst_minid)

    # 2. Install the engine WHERE minid's _vendor() looks: daemon/vendor/bubble_shield.
    #    Remove any prior copy (including a stale one from an older install layout,
    #    which is exactly the #761 trap) so we never load pre-fix code.
    if DAEMON_ENGINE_DIR.exists():
        shutil.rmtree(DAEMON_ENGINE_DIR)
    shutil.copytree(VENDOR_SRC, DAEMON_ENGINE_DIR,
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc",
                                                  "deployment_allowlist.json"))

    # 3. Sweep the OLD mismatched location if a prior install left it behind — it
    #    is on PYTHONPATH and would be an ambiguous second `bubble_shield` package.
    legacy_engine = DAEMON_SCRIPTS_DIR / "bubble_shield"
    if legacy_engine.exists():
        shutil.rmtree(legacy_engine, ignore_errors=True)
        log(f"✓ removed stale engine at legacy path: {legacy_engine}")

    # 4. Purge all bytecode under the daemon tree (belt-and-suspenders).
    n = _purge_pyc(DAEMON_ROOT)
    log(f"✓ minid + engine installed (engine → {DAEMON_ENGINE_DIR}); "
        f"purged {n} .pyc")
    return dst_minid


def _write_and_load_plist(py: str, minid: Path, host: str, root: str,
                          port: int) -> None:
    logf = BUBBLE_SHIELD_HOME / "minid.log"
    # KeepAlive UNCONDITIONAL — a read daemon must always be up. If minid exits for
    # ANY reason (crash, OOM, reboot), launchd restarts it. This is the whole point
    # of the mini tier's availability (contrast nerd/gemmad which idle-exit on
    # purpose to free RAM). PYTHONPATH points at daemon/vendor — the SAME dir
    # minid's own _vendor() resolves — so `from bubble_shield import shadow_store`
    # resolves against the one canonical vendored copy either way (belt+suspenders).
    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>{MINID_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{py}</string>
    <string>{minid}</string>
    <string>--host</string><string>{host}</string>
    <string>--root</string><string>{root}</string>
    <string>--port</string><string>{port}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>BUBBLE_SHIELD_HOME</key><string>{BUBBLE_SHIELD_HOME}</string>
    <key>PYTHONPATH</key><string>{DAEMON_VENDOR_DIR}</string>
    <key>BUBBLE_SHIELD_SILENCE_PLAINTEXT_WARN</key><string>1</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key><string>{logf}</string>
  <key>StandardErrorPath</key><string>{logf}</string>
</dict>
</plist>
"""
    MINID_PLIST.parent.mkdir(parents=True, exist_ok=True)
    MINID_PLIST.write_text(plist, encoding="utf-8")
    # unload-then-load so a re-run picks up new host/root/port
    subprocess.run(["launchctl", "unload", str(MINID_PLIST)], capture_output=True)
    r = subprocess.run(["launchctl", "load", str(MINID_PLIST)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        log(f"⚠️ launchctl load returned {r.returncode}: {r.stderr.strip()}")
    else:
        log(f"✓ LaunchAgent loaded ({MINID_LABEL}) — minid starts at login, "
            "restarts on any exit")


def _verify_serving(host: str, port: int, timeout_s: int = 30):
    """Poll /health until minid answers (it starts fast — no model load).

    Returns the parsed /health dict on success (so the caller can inspect
    shadow_count for the #761 self-check), or None on timeout."""
    deadline = time.monotonic() + timeout_s
    url = f"http://{host}:{port}/health"
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as r:
                import json
                d = json.loads(r.read().decode())
                if d.get("ok"):
                    log(f"✓ minid serving on {host}:{port} "
                        f"(shadows: {d.get('shadow_count', '?')})")
                    return d
        except Exception:
            time.sleep(1)
    log(f"✗ minid did NOT answer /health on {host}:{port} within {timeout_s}s — "
        f"check {BUBBLE_SHIELD_HOME / 'minid.log'}")
    return None


def _enc_store_has_content() -> bool:
    """True if an encrypted store exists AND is non-trivial (not an empty seal).

    A bare envelope over an empty DB is a few hundred bytes; a store with real
    shadows is far larger. We only need "there is encrypted content that minid
    SHOULD be able to see" — a conservative size floor separates a genuinely
    empty store (0 shadows is legitimate) from a populated one (0 shadows is the
    #761 bug: minid loaded pre-fix engine → couldn't decrypt → plaintext → 0)."""
    enc = BUBBLE_SHIELD_HOME / "shield.db.enc"
    try:
        return enc.is_file() and enc.stat().st_size > 4096
    except OSError:
        return False


def _self_check_engine_loaded(health: dict) -> None:
    """#761 guard: if the store is encrypted-and-populated but minid reports
    0 shadows, the engine loaded in a broken (plaintext-fallback) state — catch
    it at SETUP time, not weeks later in production. WARN loudly; do not fail the
    install (a legitimately empty store also reports 0, so this stays a warning,
    but the enc-has-content precondition makes a false alarm unlikely)."""
    count = health.get("shadow_count")
    if _enc_store_has_content() and count == 0:
        log("")
        log("⚠️  ⚠️  #761 SIGNATURE: encrypted store has content but minid sees "
            "0 shadows.")
        log("    minid likely loaded a STALE/plaintext engine and cannot decrypt "
            "shield.db.enc.")
        log(f"    → check {BUBBLE_SHIELD_HOME / 'minid.log'}; confirm the engine "
            f"at {DAEMON_ENGINE_DIR}")
        log("      is fresh and that a passphrase is resolvable (keychain/SOPS). "
            "READ TIER IS DEGRADED.")
        log("")
    elif count == 0:
        log("ℹ️  minid reports 0 shadows (store is empty or not yet encrypted — "
            "expected on a fresh vault).")


def uninstall() -> int:
    subprocess.run(["launchctl", "unload", str(MINID_PLIST)], capture_output=True)
    if MINID_PLIST.exists():
        MINID_PLIST.unlink()
    log(f"✓ minid LaunchAgent removed ({MINID_LABEL})")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", help="the mini's Tailscale IP (tailscale ip -4)")
    ap.add_argument("--root", help="protected vault root (Dropbox clients folder)")
    ap.add_argument("--port", type=int, default=8377)
    ap.add_argument("--uninstall", action="store_true")
    args = ap.parse_args()

    if args.uninstall:
        return uninstall()
    if not args.host or not args.root:
        ap.error("--host and --root are required (unless --uninstall)")
    if args.host in ("0.0.0.0", "::"):
        log("✗ refuse to bind all interfaces — pass the Tailscale IP")
        return 2
    root = str(Path(os.path.expanduser(args.root)).resolve())
    if not Path(root).is_dir():
        log(f"✗ --root is not a directory: {root}")
        return 2

    log("Bubble Shield — Mac-mini read-distribution tier setup")
    log(f"  home: {BUBBLE_SHIELD_HOME}")
    log(f"  host: {args.host}  port: {args.port}")
    log(f"  root: {root}")

    py = sys.executable  # stock python3 is fine — minid is stdlib + pure-python engine
    minid = _install_to_stable_path()
    _write_and_load_plist(py, minid, args.host, root, args.port)
    health = _verify_serving(args.host, args.port)
    ok = health is not None
    if ok:
        _self_check_engine_loaded(health)

    if ok:
        tok = (BUBBLE_SHIELD_HOME / "mini_token")
        log("\n✅ Mini tier ready. Next:")
        log(f"  • Bearer token (paste into each employee's config): "
            f"{'see ' + str(tok) if tok.is_file() else '(generated on first request)'}")
        log(f"  • Each employee sets mini_url=http://{args.host}:{args.port} + token")
        log(f"  • minid auto-starts at login + restarts on any exit (KeepAlive).")
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
